sonar.projectKey=OmkarNCI_campus_portal
sonar.organization=omkarnci
sonar.projectName=campus_portal
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/migrations/**,**/venv/**,**/static/**,**/media/**,**/__pycache__/**,manage.py

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml