# Generated by Django 5.2.12 on 2026-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_rename_card_id_student_cardid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
